version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: 913519/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    depends_on:
      - "manage"
    volumes:
     - ./etc/openvpn/server:/etc/openvpn/server
  manage:
    image: 913519/openvpn-manage
    container_name: openvpn-manage
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - ./etc/openvpn/server:/etc/openvpn/server
     - ./openvpn-data/db:/opt/openvpn-manage/db
