version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: ljt0515/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
     - "5556:5556/tcp"
    restart: always
    depends_on:
      - "manage"
    volumes:
     - ./opt/openvpn/server:/opt/openvpn/server
  manage:
    image: ljt0515/openvpn-manage
    container_name: openvpn-manage
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - ./opt/openvpn/server:/opt/openvpn/server
     - ./opt/openvpn/db:/opt/openvpn-manage/db
