version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: 913519/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    depends_on:
      - "gui"
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
  gui:
    image: 913519/openvpn-manage
    container_name: openvpn-manage
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn/server
     - ./openvpn-data/db:/opt/openvpn-manage/db
